export const CONST_ADVANCE_PAYMENT_PRICE = 1000;

export const CONST_STANDARD_COURSE_PRICE = 3000;
export const CONST_EXCLUSIVE_COURSE_PRICE = 5000;

export const CONST_STANDARD_COURSE_RATES_PRICE = 3500;
export const CONST_EXCLUSIVE_COURSE_RATES_PRICE = 5500;