export const CONST_ADVANCE_PAYMENT_PRICE = 5;

export const CONST_STANDARD_COURSE_PRICE = 3000;
export const CONST_EXCLUSIVE_COURSE_PRICE = 5000;

export const CONST_STANDARD_COURSE_RATES = 3500;
export const CONST_EXCLUSIVE_COURSE_RATES = 5500;